import { ServiceImages } from "@/interfaces/services/services.interface";

/**
 * The key string is the id of the service.
 */
//TODO: Populate the images as soon as edrian sends the images
const SERVICES_GALLERY: Record<string, ServiceImages> = {
  service1: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service1",
  },
  service2: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service2",
  },
  service3: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service3",
  },
  service4: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service4",
  },
  service5: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service5",
  },
  service6: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service6",
  },
  service7: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service7",
  },
  service8: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service8",
  },
  service9: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service9",
  },
  service10: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service10",
  },
  service11: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service11",
  },
  service12: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service12",
  },
  service13: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service13",
  },
  service14: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service14",
  },
  service15: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service15",
  },
  service16: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service16",
  },
  service17: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service17",
  },
  service18: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service18",
  },
  service19: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service19",
  },
  service20: {
    images: [
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967377/my-uploads/nextgen/Editable_3D_text_effect_for_Christmas_on_a_red_and_snowy_background_z5t47l.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/MAIN_ANNOUNCEMENT_x0kghw.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/COSPLAY_POSTER_mf5d6c.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967376/my-uploads/nextgen/LOL_FB_POSTER_rojrnv.png",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/merdeka03_text_effect_c7z2sl.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/stand_up_comedy_wcalf3.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967375/my-uploads/nextgen/3d_logo_for_children_s_day_campaigns_isolated_on_light_blue_background_n1l780.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/Legend_Quest_Text_Effect_htrbpg.jpg",
      "https://res.cloudinary.com/dop8qsdej/image/upload/v1727967374/my-uploads/nextgen/kahidlaw_ex_tg7t6q.jpg",
    ],
    serviceId: "service20",
  },
};
export { SERVICES_GALLERY };
