import { Reviews } from "@/interfaces/services/services.interface";

/**
 * The key string is the service
 */
const SERVICES_REVIEWS: Record<string, Reviews[]> = {
  service1: [
    {
      serviceReviewsId: "review1",
      projectStatus: "FINISHED",
      serviceId: "service1",
      reviewerId: "userId1",
      rating: 5,
      comment: "Excellent SEO strategies that really improved my site traffic!",
      createdAt: new Date(),
      likes: ["userId2", "userId3"],
    },
    {
      serviceReviewsId: "review2",
      projectStatus: "FINISHED",
      serviceId: "service1",
      reviewerId: "partnerId1",
      rating: 2,
      comment:
        "I was really disappointed with the service. Communication was lacking, and I didn't see the results I hoped for. Would not recommend.",
      createdAt: new Date(),
      likes: ["userId4"],
    },
    {
      serviceReviewsId: "review3",
      projectStatus: "FINISHED",
      serviceId: "service1",
      reviewerId: "userId2",
      rating: 4,
      comment:
        "Good service overall but could have used more detailed reports.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review4",
      projectStatus: "FINISHED",
      serviceId: "service1",
      reviewerId: "partnerId2",
      rating: 3,
      comment:
        "Mixed feelings. Some strategies worked well, while others were lackluster.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review5",
      projectStatus: "FINISHED",
      serviceId: "service1",
      reviewerId: "userId3",
      rating: 5,
      comment:
        "Top-notch service! The team was very knowledgeable and responsive.",
      createdAt: new Date(),
      likes: ["userId5"],
    },
    {
      serviceReviewsId: "review6",
      projectStatus: "FINISHED",
      serviceId: "service1",
      reviewerId: "partnerId3",
      rating: 4,
      comment: "Great results, but I wish the process was faster.",
      createdAt: new Date(),
      likes: [],
    },
  ],
  service2: [
    {
      serviceReviewsId: "review7",
      projectStatus: "FINISHED",
      serviceId: "service2",
      reviewerId: "userId4",
      rating: 4,
      comment: "Great content marketing! My audience engagement has increased.",
      createdAt: new Date(),
      likes: ["userId6", "partnerId4"],
    },
    {
      serviceReviewsId: "review8",
      projectStatus: "FINISHED",
      serviceId: "service2",
      reviewerId: "partnerId4",
      rating: 3,
      comment:
        "The campaign had potential but ultimately fell short. Hoping for better next time.",
      createdAt: new Date(),
      likes: ["userId7"],
    },
    {
      serviceReviewsId: "review9",
      projectStatus: "FINISHED",
      serviceId: "service2",
      reviewerId: "userId5",
      rating: 5,
      comment:
        "Creative ideas that led to successful campaigns. Highly recommended!",
      createdAt: new Date(),
      likes: ["userId8"],
    },
    {
      serviceReviewsId: "review10",
      projectStatus: "FINISHED",
      serviceId: "service2",
      reviewerId: "userId6",
      rating: 4,
      comment:
        "The team was responsive and provided good support, but I wanted more data insights.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review11",
      projectStatus: "FINISHED",
      serviceId: "service2",
      reviewerId: "userId7",
      rating: 4,
      comment:
        "Solid work, but I think the strategy could have been executed better.",
      createdAt: new Date(),
      likes: ["userId3"],
    },
    {
      serviceReviewsId: "review12",
      projectStatus: "FINISHED",
      serviceId: "service2",
      reviewerId: "userId8",
      rating: 2,
      comment:
        "Very dissatisfied with the outcome. Expected much more based on the initial discussions.",
      createdAt: new Date(),
      likes: [],
    },
  ],
  service3: [
    {
      serviceReviewsId: "review13",
      projectStatus: "FINISHED",
      serviceId: "service3",
      reviewerId: "userId9",
      rating: 3,
      comment:
        "The social media management was decent but could use more posts.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review14",
      projectStatus: "FINISHED",
      serviceId: "service3",
      reviewerId: "userId10",
      rating: 5,
      comment: "Fantastic engagement tactics! Highly recommended.",
      createdAt: new Date(),
      likes: ["userId2"],
    },
    {
      serviceReviewsId: "review15",
      projectStatus: "FINISHED",
      serviceId: "service3",
      reviewerId: "userId1",
      rating: 4,
      comment:
        "Good overall service but lacking in some areas of strategy execution.",
      createdAt: new Date(),
      likes: ["userId3"],
    },
    {
      serviceReviewsId: "review16",
      projectStatus: "FINISHED",
      serviceId: "service3",
      reviewerId: "partnerId5",
      rating: 2,
      comment:
        "The results were disappointing, and the communication was poor.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review17",
      projectStatus: "FINISHED",
      serviceId: "service3",
      reviewerId: "userId3",
      rating: 4,
      comment: "Great content creation, but I expected more frequency.",
      createdAt: new Date(),
      likes: ["userId6"],
    },
    {
      serviceReviewsId: "review18",
      projectStatus: "FINISHED",
      serviceId: "service3",
      reviewerId: "partnerId4",
      rating: 5,
      comment:
        "Very professional and easy to work with. Will continue to use their services.",
      createdAt: new Date(),
      likes: [],
    },
  ],
  service4: [
    {
      serviceReviewsId: "review19",
      projectStatus: "FINISHED",
      serviceId: "service4",
      reviewerId: "userId2",
      rating: 4,
      comment: "Effective PPC campaigns that increased my sales.",
      createdAt: new Date(),
      likes: ["partnerId3"],
    },
    {
      serviceReviewsId: "review20",
      projectStatus: "FINISHED",
      serviceId: "service4",
      reviewerId: "userId1",
      rating: 5,
      comment:
        "Great communication and fast results! Very pleased with the outcome.",
      createdAt: new Date(),
      likes: ["userId4"],
    },
    {
      serviceReviewsId: "review21",
      projectStatus: "FINISHED",
      serviceId: "service4",
      reviewerId: "userId5",
      rating: 3,
      comment:
        "The service is average. I'm looking for more innovative strategies.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review22",
      projectStatus: "FINISHED",
      serviceId: "service4",
      reviewerId: "partnerId2",
      rating: 2,
      comment:
        "I was not satisfied with the results, and the follow-up was poor.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review23",
      projectStatus: "FINISHED",
      serviceId: "service4",
      reviewerId: "userId6",
      rating: 5,
      comment: "Exceptional service and results that exceeded my expectations!",
      createdAt: new Date(),
      likes: ["userId7"],
    },
    {
      serviceReviewsId: "review24",
      projectStatus: "FINISHED",
      serviceId: "service4",
      reviewerId: "partnerId3",
      rating: 4,
      comment:
        "Good strategies, but could use more creative ideas in the campaigns.",
      createdAt: new Date(),
      likes: [],
    },
  ],
  service5: [
    {
      serviceReviewsId: "review25",
      projectStatus: "FINISHED",
      serviceId: "service5",
      reviewerId: "userId7",
      rating: 5,
      comment: "Incredible web design! My site looks amazing now.",
      createdAt: new Date(),
      likes: ["userId8"],
    },
    {
      serviceReviewsId: "review26",
      projectStatus: "FINISHED",
      serviceId: "service5",
      reviewerId: "userId8",
      rating: 4,
      comment:
        "Great design and user experience, but the turnaround time could be faster.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review27",
      projectStatus: "FINISHED",
      serviceId: "service5",
      reviewerId: "userId9",
      rating: 2,
      comment:
        "Not happy with the final product. It didn't meet my expectations.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review28",
      projectStatus: "FINISHED",
      serviceId: "service5",
      reviewerId: "partnerId1",
      rating: 3,
      comment: "Decent work, but I expected more creativity.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review29",
      projectStatus: "FINISHED",
      serviceId: "service5",
      reviewerId: "userId10",
      rating: 4,
      comment: "The design looks good, but I'm waiting for some adjustments.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review30",
      projectStatus: "FINISHED",
      serviceId: "service5",
      reviewerId: "userId4",
      rating: 5,
      comment: "Highly recommend! They went above and beyond.",
      createdAt: new Date(),
      likes: ["userId2"],
    },
  ],
  service6: [
    {
      serviceReviewsId: "review30",
      projectStatus: "FINISHED",
      serviceId: "service6",
      reviewerId: "userId1",
      rating: 5,
      comment:
        "The website development service exceeded my expectations! They took the time to understand my brand, and the final product is stunning.",
      createdAt: new Date(),
      likes: ["userId2", "userId3"],
    },
    {
      serviceReviewsId: "review31",
      projectStatus: "FINISHED",
      serviceId: "service6",
      reviewerId: "userId2",
      rating: 4,
      comment:
        "Good service but took longer than expected. The end result was great, but I wish the process was smoother.",
      createdAt: new Date(),
      likes: ["userId3"],
    },
    {
      serviceReviewsId: "review32",
      projectStatus: "FINISHED",
      serviceId: "service6",
      reviewerId: "partnerId1",
      rating: 2,
      comment:
        "I had to cancel my project midway due to miscommunication. They had great ideas but struggled with execution.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review33",
      projectStatus: "FINISHED",
      serviceId: "service6",
      reviewerId: "userId4",
      rating: 3,
      comment:
        "The team was responsive and addressed most of my concerns. My website looks professional now, but there were some minor bugs initially.",
      createdAt: new Date(),
      likes: ["userId2"],
    },
    {
      serviceReviewsId: "review34",
      projectStatus: "FINISHED",
      serviceId: "service6",
      reviewerId: "userId5",
      rating: 4,
      comment:
        "Overall a good experience. The design was aligned with my vision, though some features were not implemented as requested.",
      createdAt: new Date(),
      likes: ["userId3"],
    },
    {
      serviceReviewsId: "review35",
      projectStatus: "FINISHED",
      serviceId: "service6",
      reviewerId: "userId6",
      rating: 4,
      comment:
        "I loved the website they developed for me! They were very patient with all my changes.",
      createdAt: new Date(),
      likes: ["userId1", "userId4"],
    },
  ],
  service7: [
    {
      serviceReviewsId: "review36",
      projectStatus: "FINISHED",
      serviceId: "service7",
      reviewerId: "userId2",
      rating: 5,
      comment:
        "The social media management service boosted our engagement significantly. They understand trends really well!",
      createdAt: new Date(),
      likes: ["userId1", "userId3"],
    },
    {
      serviceReviewsId: "review37",
      projectStatus: "FINISHED",
      serviceId: "service7",
      reviewerId: "userId3",
      rating: 4,
      comment:
        "Great content creation, though I wish they had more frequent updates. Overall, I’m satisfied.",
      createdAt: new Date(),
      likes: ["userId4"],
    },
    {
      serviceReviewsId: "review38",
      projectStatus: "FINISHED",
      serviceId: "service7",
      reviewerId: "partnerId2",
      rating: 2,
      comment:
        "I had to stop the service because the posts were not resonating with our audience.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review39",
      projectStatus: "FINISHED",
      serviceId: "service7",
      reviewerId: "userId4",
      rating: 5,
      comment:
        "The campaign they ran was successful, and they handled everything seamlessly. Highly recommended!",
      createdAt: new Date(),
      likes: ["userId5"],
    },
    {
      serviceReviewsId: "review40",
      projectStatus: "FINISHED",
      serviceId: "service7",
      reviewerId: "userId5",
      rating: 3,
      comment:
        "Good service but not very innovative. I expected more creative strategies.",
      createdAt: new Date(),
      likes: ["userId1"],
    },
    {
      serviceReviewsId: "review41",
      projectStatus: "FINISHED",
      serviceId: "service7",
      reviewerId: "userId6",
      rating: 4,
      comment:
        "Responsive team and good communication, but the creative aspects could improve.",
      createdAt: new Date(),
      likes: ["userId3"],
    },
  ],
  service8: [
    {
      serviceReviewsId: "review42",
      projectStatus: "FINISHED",
      serviceId: "service8",
      reviewerId: "userId1",
      rating: 5,
      comment:
        "The branding service transformed our identity. Our new logo and colors perfectly reflect our mission.",
      createdAt: new Date(),
      likes: ["userId2", "userId3"],
    },
    {
      serviceReviewsId: "review43",
      projectStatus: "FINISHED",
      serviceId: "service8",
      reviewerId: "userId2",
      rating: 4,
      comment:
        "I was impressed with their insights into our brand strategy. A few adjustments were needed, but overall a positive experience.",
      createdAt: new Date(),
      likes: ["userId4"],
    },
    {
      serviceReviewsId: "review44",
      projectStatus: "FINISHED",
      serviceId: "service8",
      reviewerId: "partnerId1",
      rating: 3,
      comment:
        "The service was decent but didn't quite meet our expectations. They were responsive but lacked creativity.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review45",
      projectStatus: "FINISHED",
      serviceId: "service8",
      reviewerId: "userId3",
      rating: 4,
      comment:
        "Very professional team, and they helped us define our brand voice clearly. Some delays, though.",
      createdAt: new Date(),
      likes: ["userId1"],
    },
    {
      serviceReviewsId: "review46",
      projectStatus: "FINISHED",
      serviceId: "service8",
      reviewerId: "userId4",
      rating: 5,
      comment:
        "Outstanding work! The new branding materials have received positive feedback from our customers.",
      createdAt: new Date(),
      likes: ["userId2"],
    },
  ],
  service9: [
    {
      serviceReviewsId: "review47",
      projectStatus: "FINISHED",
      serviceId: "service9",
      reviewerId: "userId1",
      rating: 4,
      comment:
        "Great graphic design service! They delivered on time and the designs are eye-catching.",
      createdAt: new Date(),
      likes: ["userId2", "userId3"],
    },
    {
      serviceReviewsId: "review48",
      projectStatus: "FINISHED",
      serviceId: "service9",
      reviewerId: "userId2",
      rating: 5,
      comment:
        "The team understood our vision perfectly and brought it to life! Highly recommend for any design needs.",
      createdAt: new Date(),
      likes: ["userId1", "userId4"],
    },
    {
      serviceReviewsId: "review49",
      projectStatus: "FINISHED",
      serviceId: "service9",
      reviewerId: "partnerId2",
      rating: 3,
      comment:
        "The graphics were good but not what I initially expected. There were some revisions needed.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review50",
      projectStatus: "FINISHED",
      serviceId: "service9",
      reviewerId: "userId3",
      rating: 4,
      comment:
        "I was pleased with the final designs, although the communication could have been better.",
      createdAt: new Date(),
      likes: ["userId2"],
    },
    {
      serviceReviewsId: "review51",
      projectStatus: "FINISHED",
      serviceId: "service9",
      reviewerId: "userId4",
      rating: 5,
      comment:
        "Exceptional work! Our marketing materials look fantastic, and they captured our brand essence beautifully.",
      createdAt: new Date(),
      likes: ["userId1"],
    },
  ],
  service10: [
    {
      serviceReviewsId: "review52",
      projectStatus: "FINISHED",
      serviceId: "service10",
      reviewerId: "userId1",
      rating: 5,
      comment:
        "The influencer marketing service was top-notch. They connected us with the right influencers and our engagement skyrocketed!",
      createdAt: new Date(),
      likes: ["userId2", "userId3"],
    },
    {
      serviceReviewsId: "review53",
      projectStatus: "FINISHED",
      serviceId: "service10",
      reviewerId: "userId2",
      rating: 4,
      comment:
        "Great results, but the process took longer than I anticipated. The influencers they chose were perfect for our brand.",
      createdAt: new Date(),
      likes: ["userId4"],
    },
    {
      serviceReviewsId: "review54",
      projectStatus: "FINISHED",
      serviceId: "service10",
      reviewerId: "partnerId1",
      rating: 2,
      comment:
        "I had to cancel because the influencer partnerships were not aligned with our goals.",
      createdAt: new Date(),
      likes: [],
    },
    {
      serviceReviewsId: "review55",
      projectStatus: "FINISHED",
      serviceId: "service10",
      reviewerId: "userId3",
      rating: 4,
      comment:
        "Effective campaigns and good communication, although we had to provide a lot of input.",
      createdAt: new Date(),
      likes: ["userId1"],
    },
    {
      serviceReviewsId: "review56",
      projectStatus: "FINISHED",
      serviceId: "service10",
      reviewerId: "userId4",
      rating: 5,
      comment:
        "Fantastic experience! They truly know how to leverage influencers for maximum impact.",
      createdAt: new Date(),
      likes: ["userId2"],
    },
    {
      serviceReviewsId: "review57",
      projectStatus: "FINISHED",
      serviceId: "service10",
      reviewerId: "userId5",
      rating: 4,
      comment:
        "Great results! The influencers they paired us with were authentic and engaging.",
      createdAt: new Date(),
      likes: ["userId3"],
    },
  ],

  service17: [
    {
      serviceReviewsId: "review48",
      projectStatus: "FINISHED",
      serviceId: "service17",
      reviewerId: "userId1",
      rating: 5,
      comment:
        "Amazing results! My affiliate campaign saw a huge boost in traffic.",
      createdAt: new Date(),
      likes: ["userId3", "userId6"],
    },
    {
      serviceReviewsId: "review49",
      projectStatus: "FINISHED",
      serviceId: "service17",
      reviewerId: "userId4",
      rating: 4,
      comment:
        "Solid work, though it took a bit longer than expected to ramp up.",
      createdAt: new Date(),
      likes: ["userId2"],
    },
    {
      serviceReviewsId: "review50",
      projectStatus: "FINISHED",
      serviceId: "service17",
      reviewerId: "partnerId5",
      rating: 3,
      comment: "Good service but lacked customization for my niche market.",
      createdAt: new Date(),
      likes: [],
    },
  ],
  service18: [
    {
      serviceReviewsId: "review51",
      projectStatus: "FINISHED",
      serviceId: "service18",
      reviewerId: "userId2",
      rating: 4,
      comment:
        "Excellent affiliate network setup. Very easy to track conversions.",
      createdAt: new Date(),
      likes: ["userId5"],
    },
    {
      serviceReviewsId: "review52",
      projectStatus: "FINISHED",
      serviceId: "service18",
      reviewerId: "userId6",
      rating: 5,
      comment:
        "Great work! Saw results almost immediately after the campaign started.",
      createdAt: new Date(),
      likes: ["userId7", "userId1"],
    },
    {
      serviceReviewsId: "review53",
      projectStatus: "FINISHED",
      serviceId: "service18",
      reviewerId: "partnerId3",
      rating: 4,
      comment:
        "Good campaign setup, but more detailed reporting would have been useful.",
      createdAt: new Date(),
      likes: [],
    },
  ],
  service19: [
    {
      serviceReviewsId: "review54",
      projectStatus: "FINISHED",
      serviceId: "service19",
      reviewerId: "userId3",
      rating: 5,
      comment: "Impressive reach for my affiliate program! Highly recommended.",
      createdAt: new Date(),
      likes: ["userId4", "userId6"],
    },
    {
      serviceReviewsId: "review55",
      projectStatus: "FINISHED",
      serviceId: "service19",
      reviewerId: "userId7",
      rating: 4,
      comment: "Good results but some affiliates were slow to engage.",
      createdAt: new Date(),
      likes: ["userId1"],
    },
    {
      serviceReviewsId: "review56",
      projectStatus: "FINISHED",
      serviceId: "service19",
      reviewerId: "partnerId6",
      rating: 3,
      comment: "Average results. The campaign could have been better managed.",
      createdAt: new Date(),
      likes: [],
    },
  ],
  service20: [
    {
      serviceReviewsId: "review57",
      projectStatus: "FINISHED",
      serviceId: "service20",
      reviewerId: "userId5",
      rating: 4,
      comment: "Very good campaign setup, helped me attract more affiliates.",
      createdAt: new Date(),
      likes: ["userId9"],
    },
    {
      serviceReviewsId: "review58",
      projectStatus: "FINISHED",
      serviceId: "service20",
      reviewerId: "userId8",
      rating: 5,
      comment: "Great service, my affiliate program is now running smoothly!",
      createdAt: new Date(),
      likes: ["userId3", "userId7"],
    },
    {
      serviceReviewsId: "review59",
      projectStatus: "FINISHED",
      serviceId: "service20",
      reviewerId: "partnerId7",
      rating: 4,
      comment: "Effective campaign but could improve on reporting metrics.",
      createdAt: new Date(),
      likes: [],
    },
  ],
};

export { SERVICES_REVIEWS };
